const actions = [
  {
    id: "confirm-entry",
    phase: "before",
    title: "Confirm your event entry",
    description: "Verify the participant name, category, emergency contact, and registration status.",
    deadline: "September 7 · 18:00",
    estimatedMinutes: 4,
    required: true,
    critical: true,
    official: true,
  },
  {
    id: "travel-plan",
    phase: "before",
    title: "Define your arrival plan",
    description: "Choose a route that gets you to Harbor Park before the transition area closes.",
    deadline: "September 9",
    estimatedMinutes: 8,
    required: true,
    critical: false,
    official: true,
  },
  {
    id: "medical-check",
    phase: "before",
    title: "Review the health and safety protocol",
    description: "Read the heat, hydration, medication, and withdrawal guidance before race day.",
    deadline: "September 10",
    estimatedMinutes: 6,
    required: true,
    critical: true,
    official: true,
  },
  {
    id: "swim-gear",
    phase: "before",
    title: "Prepare your swim equipment",
    description: "Confirm goggles, cap, timing chip plan, towel, and permitted racewear.",
    deadline: "September 11",
    estimatedMinutes: 7,
    required: true,
    critical: false,
    official: true,
  },
  {
    id: "bike-gear",
    phase: "before",
    title: "Complete the bicycle safety check",
    description: "Inspect brakes, tires, helmet, bottles, lights, and the race number attachment.",
    deadline: "September 11",
    estimatedMinutes: 10,
    required: true,
    critical: true,
    official: true,
  },
  {
    id: "recovery-assessment",
    phase: "before",
    title: "Book an optional recovery assessment",
    description: "A mobility screening can help you identify avoidable discomfort before the event.",
    deadline: "September 10",
    estimatedMinutes: 5,
    required: false,
    critical: false,
    official: false,
    sponsored: {
      partner: "MotionLab Demo",
      disclosure: "Synthetic sponsored action",
      value: "Complimentary 15-minute mobility screening",
    },
  },
  {
    id: "athlete-briefing",
    phase: "before",
    title: "Attend the official athlete briefing",
    description: "Review the course, start waves, penalties, weather protocol, and emergency channels.",
    deadline: "September 11 · 19:00",
    estimatedMinutes: 18,
    required: true,
    critical: true,
    official: true,
  },
  {
    id: "transition-entry",
    phase: "during",
    title: "Enter transition before closing time",
    description: "Present your race ID and place equipment only in your assigned position.",
    deadline: "September 12 · 05:45",
    estimatedMinutes: 12,
    required: true,
    critical: true,
    official: true,
  },
  {
    id: "course-checkpoints",
    phase: "during",
    title: "Follow the official course checkpoints",
    description: "Use the marked route and report incidents through the official safety points.",
    deadline: "September 12",
    estimatedMinutes: 3,
    required: true,
    critical: true,
    official: true,
  },
  {
    id: "post-event-checkout",
    phase: "after",
    title: "Complete post-event checkout",
    description: "Collect equipment, verify timing status, and report any medical or safety incident.",
    deadline: "September 12 · 14:00",
    estimatedMinutes: 8,
    required: true,
    critical: false,
    official: true,
  },
];

export const initialState = {
  mode: "participant",
  guide: {
    id: "coastal-5150-demo",
    title: "Coastal 5150 — Demo Event",
    organizer: "Harbor Sports Lab (synthetic)",
    outcome: "Arrive prepared, complete the event safely, and close out every official step.",
    eventDate: "September 12, 2026",
    location: "Harbor Park · Demo City",
    status: "published",
    version: "1.0",
    updatedAt: "2026-08-30T12:00:00.000Z",
    actions,
  },
  participant: {
    name: "Demo Participant",
    experience: "first-time",
    availableMinutes: 45,
    accessibilityNeeds: "Prefer low-impact transitions and concise instructions.",
  },
  completedActionIds: ["confirm-entry", "travel-plan"],
  personalPlan: [],
  pendingChanges: [],
  sponsorEngagements: [],
  audit: [
    {
      id: "audit-initial",
      at: "2026-08-30T12:00:00.000Z",
      actor: "system",
      kind: "demo_loaded",
      summary: "Synthetic official guide loaded",
    },
  ],
};

export function freshInitialState() {
  return structuredClone(initialState);
}
