export const creationBrief = {
  id: "brief-coastal-5150",
  label: "Organizer notes · synthetic challenge scenario",
  raw: `We are organizing the Coastal 5150 on September 12 at Harbor Park. Most participants are first-timers, so the experience must feel clear, encouraging, and personal. They must confirm registration and emergency information, plan arrival before transition closes at 5:45 a.m., review heat and hydration rules, prepare swim gear, and complete a bicycle safety check. During the event they must use official checkpoints; afterward they collect equipment and report incidents. We want a clearly disclosed mobility or recovery partner to help at a useful moment, never make a purchase mandatory, and give sponsors more accurate audience-intent signals through real contextual interest and explicit opt-ins—not inferred profiles alone. We also want a share-worthy prize for people who complete every required preparation step, so verified achievement becomes an organic hook for event virality through a clean Ready Pass referral. Flag anything the organizer still needs to confirm.`,
  source: "Synthetic organizer brief",
  updatedAt: "2026-08-30T12:00:00.000Z",
};

const actions = [
  {
    id: "confirm-entry",
    phase: "before",
    title: "Confirm your event entry",
    description: "Verify your name, category, emergency contact, and registration status.",
    deadline: "September 7 · 18:00",
    estimatedMinutes: 4,
    required: true,
    critical: true,
    official: true,
    completionEvidence: "Participant confirms the four registration fields.",
    sourceRef: "Organizer registration protocol",
  },
  {
    id: "arrival-plan",
    phase: "before",
    title: "Define your arrival plan",
    description: "Choose a route that gets you to Harbor Park before transition closes.",
    deadline: "September 9",
    estimatedMinutes: 8,
    required: true,
    critical: false,
    official: true,
    completionEvidence: "Arrival route and target time are selected.",
    sourceRef: "Event access brief",
  },
  {
    id: "health-protocol",
    phase: "before",
    title: "Review the health and safety protocol",
    description: "Read the heat, hydration, medication, and withdrawal guidance.",
    deadline: "September 10",
    estimatedMinutes: 6,
    required: true,
    critical: true,
    official: true,
    completionEvidence: "Participant acknowledges the safety guidance.",
    sourceRef: "Official safety protocol",
  },
  {
    id: "swim-equipment",
    phase: "before",
    title: "Prepare your swim equipment",
    description: "Confirm goggles, cap, timing chip plan, towel, and permitted racewear.",
    deadline: "September 11",
    estimatedMinutes: 7,
    required: true,
    critical: false,
    official: true,
    completionEvidence: "All required swim items are checked.",
    sourceRef: "Athlete equipment rules",
  },
  {
    id: "bike-safety",
    phase: "before",
    title: "Complete the bicycle safety check",
    description: "Inspect brakes, tires, helmet, bottles, lights, and race-number attachment.",
    deadline: "September 11 · 20:00",
    estimatedMinutes: 10,
    required: true,
    critical: true,
    official: true,
    completionEvidence: "Participant confirms every bicycle safety item.",
    sourceRef: "Official bicycle safety checklist",
  },
  {
    id: "mobility-screening",
    phase: "before",
    title: "Fine-tune your mobility before race day",
    description: "An optional mobility and bike-fit screen can identify avoidable discomfort.",
    deadline: "September 10",
    estimatedMinutes: 5,
    required: false,
    critical: false,
    official: false,
    completionEvidence: "Participant may activate the benefit or continue without it.",
    sourceRef: "Partner value proposal",
    sponsored: {
      partner: "MotionLab Demo",
      category: "Performance & recovery",
      disclosure: "Sponsored action · Synthetic partner",
      headline: "A safer fit in fifteen minutes.",
      value: "Complimentary mobility and bike-fit screening",
      ctaLabel: "Activate demo benefit",
      terms: "Optional. No purchase required. The guide can be completed without using this benefit.",
    },
  },
  {
    id: "transition-entry",
    phase: "during",
    title: "Enter transition before closing time",
    description: "Present your race ID and place equipment only in your assigned position.",
    deadline: "September 12 · 05:45",
    estimatedMinutes: 12,
    required: true,
    critical: true,
    official: true,
    completionEvidence: "Transition access is confirmed.",
    sourceRef: "Race-day operations protocol",
  },
  {
    id: "course-checkpoints",
    phase: "during",
    title: "Follow the official course checkpoints",
    description: "Use the marked route and report incidents through official safety points.",
    deadline: "September 12",
    estimatedMinutes: 3,
    required: true,
    critical: true,
    official: true,
    completionEvidence: "Participant completes the marked course or reports withdrawal.",
    sourceRef: "Official course rules",
  },
  {
    id: "post-event-checkout",
    phase: "after",
    title: "Complete post-event checkout",
    description: "Collect equipment, verify timing status, and report medical or safety incidents.",
    deadline: "September 12 · 14:00",
    estimatedMinutes: 8,
    required: true,
    critical: false,
    official: true,
    completionEvidence: "Equipment and timing status are confirmed.",
    sourceRef: "Post-event protocol",
  },
];

export const sampleGeneratedDraft = {
  title: "Coastal 5150 — Official Preparation Guide",
  organizer: "Harbor Sports Lab (synthetic)",
  outcome: "Arrive prepared, complete the event safely, and close every official step.",
  definitionOfDone: "Every required preparation action is verified before transition opens; race-day and checkout duties remain visible until completed.",
  eventDate: "September 12, 2026",
  location: "Harbor Park · Demo City",
  sourceLabel: "Synthetic organizer brief",
  actions,
  assumptions: [
    "The event uses the local time shown in the guide.",
    "The partner benefit is illustrative and creates no external booking.",
  ],
  openQuestions: [],
  reward: {
    title: "OCHECK Ready Pass",
    unlockRule: "Complete every required Before action.",
    benefit: "Shareable proof of readiness, a synthetic recovery benefit, and a clean invitation that helps the event grow.",
    sponsor: "MotionLab Demo",
  },
};

export const initialState = {
  mode: "participant",
  brief: creationBrief,
  creation: {
    draft: null,
    validation: null,
  },
  guide: {
    id: "coastal-5150-demo",
    title: sampleGeneratedDraft.title,
    organizer: sampleGeneratedDraft.organizer,
    outcome: sampleGeneratedDraft.outcome,
    definitionOfDone: sampleGeneratedDraft.definitionOfDone,
    eventDate: sampleGeneratedDraft.eventDate,
    location: sampleGeneratedDraft.location,
    sourceLabel: sampleGeneratedDraft.sourceLabel,
    status: "published",
    version: "1.0",
    updatedAt: "2026-08-30T12:00:00.000Z",
    actions,
  },
  participant: {
    name: "Demo Participant",
    experience: "first-time",
    availableMinutes: 25,
    accessibilityNeeds: "Prefer concise instructions and low-impact transitions.",
  },
  completedActionIds: ["confirm-entry", "arrival-plan", "health-protocol", "swim-equipment"],
  personalPlan: [],
  sponsorEngagements: [],
  reward: {
    id: "ready-pass-coastal-5150",
    title: "OCHECK Ready Pass",
    status: "locked",
    unlockRule: sampleGeneratedDraft.reward.unlockRule,
    benefit: sampleGeneratedDraft.reward.benefit,
    sponsor: sampleGeneratedDraft.reward.sponsor,
    code: null,
    referralCode: null,
    claimedAt: null,
  },
  impact: {
    synthetic: true,
    guideOpens: 8420,
    activeParticipants: 6185,
    readyPasses: 5389,
    sponsorImpressions: 6940,
    sponsorActionOpens: 1720,
    sponsorActivations: 860,
    rewardShares: 2480,
    referredStarts: 786,
  },
  audit: [
    {
      id: "audit-initial",
      at: "2026-08-30T12:00:00.000Z",
      actor: "system",
      kind: "demo_loaded",
      summary: "Synthetic OCHECK outcome loaded",
    },
  ],
};

export function freshInitialState() {
  return structuredClone(initialState);
}
